version: '3.8'

services:
  code-execution:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
    restart: unless-stopped
    security_opt:
      - seccomp=unconfined
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
